In [1]:
#Refrence material 

https://www.coursera.org/learn/unsupervised-learning-recommenders-reinforcement-learning/programming/Rqh9M/anomaly-detection/lab?path=%2Fnotebooks%2FC3_W1_Anomaly_Detection.ipynb

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('final_train_data.csv')

In [4]:
df.head(5)

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0   0     L50096    L                300.6                    309.6   
1   1     M20343    M                302.6                    312.1   
2   2     L49454    L                299.3                    308.5   
3   3     L53355    L                301.0                    310.9   
4   4     M24050    M                298.0                    309.0   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1596         36.1              140                0    0   
1                    1759         29.1              200                0    0   
2                    1805         26.5               25                0    0   
3                    1524         44.3              197                0    0   
4                    1641         35.4               34                0    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0

In [5]:
df=df.drop(['id','Product ID','Machine failure'], axis=1)

In [6]:
df.head(5)

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0    L                300.6                    309.6                    1596   
1    M                302.6                    312.1                    1759   
2    L                299.3                    308.5                    1805   
3    L                301.0                    310.9                    1524   
4    M                298.0                    309.0                    1641   

   Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  OSF  RNF  
0         36.1              140    0    0    0    0    0  
1         29.1              200    0    0    0    0    0  
2         26.5               25    0    0    0    0    0  
3         44.3              197    0    0    0    0    0  
4         35.4               34    0    0    0    0    0

In [7]:
df['Type'] = df['Type'].replace({'H':0,'M':1,'L':2})

In [8]:
df.head(5)

Type  Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0     2                300.6                    309.6                    1596   
1     1                302.6                    312.1                    1759   
2     2                299.3                    308.5                    1805   
3     2                301.0                    310.9                    1524   
4     1                298.0                    309.0                    1641   

   Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  OSF  RNF  
0         36.1              140    0    0    0    0    0  
1         29.1              200    0    0    0    0    0  
2         26.5               25    0    0    0    0    0  
3         44.3              197    0    0    0    0    0  
4         35.4               34    0    0    0    0    0

In [9]:
df.shape  #We have 11 features

(132133, 11)

In [10]:
df=df.drop(['Type'], axis=1)

In [11]:
df.head(5)

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0                300.6                    309.6                    1596   
1                302.6                    312.1                    1759   
2                299.3                    308.5                    1805   
3                301.0                    310.9                    1524   
4                298.0                    309.0                    1641   

   Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  OSF  RNF  
0         36.1              140    0    0    0    0    0  
1         29.1              200    0    0    0    0    0  
2         26.5               25    0    0    0    0    0  
3         44.3              197    0    0    0    0    0  
4         35.4               34    0    0    0    0    0

In [12]:
df['TWF'].value_counts()

0    132133
Name: TWF, dtype: int64

In [13]:
# df.sample(30000,random_state=1)  #Taking random 30k values

In [14]:
#converting dataframe to array

In [15]:
x = df.to_numpy()

In [16]:
x.shape

(132133, 10)

In [17]:
def estimate_gaussian(X):
#     X -> (m,n) array -> m =examples and n=attributes
#     returns : mu -> mean and var -> variance ; (n dimensional arrays) -> (n,)
    #code:
    
    m,n=X.shape
    mu_=(1/m)*np.sum(X,axis=0)
    mu=mu_.T
    var_=np.sum(((X-mu)**2),axis=0)/m
    var=var_.T
    
    return mu,var
        
        


In [18]:
mu,var=estimate_gaussian(x)

In [19]:
mu.shape

(10,)

In [20]:
mu

array([2.99847440e+02, 3.09936064e+02, 1.52146350e+03, 4.01870549e+01,
       1.03936534e+02, 0.00000000e+00, 3.78406605e-05, 2.27043963e-05,
       3.02725284e-05, 2.24016710e-03])

In [21]:
var.shape

(10,)

In [22]:
var

array([3.44398299e+00, 1.92335262e+00, 1.82080950e+04, 6.90629176e+01,
       4.05841599e+03, 0.00000000e+00, 3.78392286e-05, 2.27038808e-05,
       3.02716120e-05, 2.23514876e-03])

In [23]:
# #Wrong function -> correct function present bellow
# #Multivariance gussian
# def multivariance_gussian(X,mu,var):
# #     X -> (m,n) array -> m =examples and n=attributes
# #     mu -> (ndarary,)
# #     var -> (ndarray,)
    
#     #code:
#     n_features=X.shape[1]
#     #constant = 1 / ((2 * np.pi) ** (n_features / 2) * np.sqrt(np.prod(var+(1e-10))))
#     constant=1
#     # Compute the exponent term of the Gaussian function
#     exponent = -np.sum(((X - mu) ** 2) / (var+(1e-10)), axis=1)
    
#     # Compute the probabilities for each sample
#     probabilities = constant * np.exp(exponent)
    
#     return probabilities
    

In [24]:
# constant = 1 / (1 * np.sqrt(np.prod(var+(1e-10))))   #This is wrong

In [25]:
# constant

In [26]:
# var

In [27]:
# multiple=[]
# for i in range(len(var)):
#     if var[i]==0:
#         multiple.append(10**(10))
#     else :
#         multiple.append((1/var[i]))
        
        

In [28]:
# multiple

In [29]:
# exponent = -((x - mu) ** 2) / (var+(1e-10))

In [30]:
# exponent.shape

In [31]:
# pow_term=np.exp(exponent)

In [32]:
# pow_term.shape

In [33]:
# arr=multiple*pow_term

In [34]:
# arr.shape

In [35]:
# result = np.prod(arr, axis=1)

In [36]:
# result.shape

In [37]:
#Multivariance gussian
def multivariance_gussian(X,mu,var):
#     X -> (m,n) array -> m =examples and n=attributes
#     mu -> (ndarary,)
#     var -> (ndarray,)
    
    #code:
    n_features=X.shape[1]
    #constant = 1 / ((2 * np.pi) ** (n_features / 2) * np.sqrt(np.prod(var+(1e-10))))
    #constant=1
    multiple=[]                      # array of 1/var basically
    for i in range(len(var)):
        if var[i]==0:
            multiple.append(10**(10))
        else :
            multiple.append((1/var[i]))
        
    # Compute the exponent term of the Gaussian function
    #exponent = -np.sum(((X - mu) ** 2) / (var+(1e-10)), axis=1)
    exponent = -((X - mu) ** 2) / (var+(1e-10))
    pow_term=np.exp(exponent)
    gaussian_array=multiple*pow_term
    
    
    # Compute the probabilities for each sample
    #probabilities = constant * np.exp(exponent)
    probabilities = np.prod(gaussian_array, axis=1)
    
    return probabilities
    

In [38]:
#Getting mean and variance of the dataset
mu,var=estimate_gaussian(x)

In [39]:
p=multivariance_gussian(x,mu,var)

In [40]:
p.shape

(132133,)

In [41]:
# #Selecting an epsilon for detecting threshold
# def select_threshold(y_val, p_val): 
#     """
#     Finds the best threshold to use for selecting outliers 
#     based on the results from a validation set (p_val) 
#     and the ground truth (y_val)
    
#     Args:
#         y_val (ndarray): Ground truth on validation set
#         p_val (ndarray): Results on validation set
        
#     Returns:
#         epsilon (float): Threshold chosen 
#         F1 (float):      F1 score by choosing epsilon as threshold
#     """ 

#     best_epsilon = 0
#     best_F1 = 0
#     F1 = 0
    
#     step_size = (max(p_val) - min(p_val)) / 1000
    
#     for epsilon in np.arange(min(p_val), max(p_val), step_size):
    
#         ### START CODE HERE ### 
#         predictions = (p_val < epsilon)
#         tp = np.sum((predictions == 1) & (y_val == 1))
#         fn = np.sum((predictions == 0) & (y_val == 1))
#         fp = np.sum((predictions == 1) & (y_val == 0))
#         prec = tp / (tp + fp)
#         rec = tp / (tp + fn)
#         F1 = 2 * prec * rec / (prec + rec)
        
        
#         ### END CODE HERE ### 
        
#         if F1 > best_F1:
#             best_F1 = F1
#             best_epsilon = epsilon
        
#     return best_epsilon, best_F1

In [42]:
#Selecting an epsilon for detecting threshold
def select_threshold(y_val, p_val): 
    """
    Finds the best threshold to use for selecting outliers 
    based on the results from a validation set (p_val) 
    and the ground truth (y_val)
    
    Args:
        y_val (ndarray): Ground truth on validation set
        p_val (ndarray): Results on validation set
        
    Returns:
        epsilon (float): Threshold chosen 
        F1 (float):      F1 score by choosing epsilon as threshold
    """ 

    best_epsilon = 0
    best_F1 = 0
    F1 = 0
   
    step_size = (max(p_val) - min(p_val)) / 1000
    
    for epsilon in np.arange(min(p_val)+step_size*10, max(p_val), step_size):
    
        ### START CODE HERE ### 
        predictions = (p_val < epsilon)
        predictions = predictions.astype(int)
        tp = np.sum((predictions == 1) & (y_val == 1))
        fn = np.sum((predictions == 0) & (y_val == 1))
        fp = np.sum((predictions == 1) & (y_val == 0))
        prec = tp / (tp + fp)
        rec = tp / (tp + fn)
        F1 = 2 * prec * rec / (prec + rec)
        
        
        ### END CODE HERE ### 
        
        if F1 > best_F1:
            best_F1 = F1
            best_epsilon = epsilon
        
    return best_epsilon, best_F1

In [43]:
df_cv=pd.read_csv('final_test_data_.csv')

In [44]:
df_cv.head(5)

id Product ID Type  Air temperature [K]  Process temperature [K]  \
0   36060     L49085    L                297.9                    307.6   
1  108794     L50624    L                301.7                    310.5   
2   63513     L54341    L                300.2                    310.2   
3  129601     L53240    L                300.9                    310.9   
4    9655     L51054    L                302.4                    311.8   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1448         48.6              176                0    0   
1                    1402         38.9                0                0    0   
2                    1378         60.3              200                1    0   
3                    1429         47.0              199                0    0   
4                    1307         55.5                5                1    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    1    0  
3    0    0    0    0  
4    1    0    0    0

In [45]:
df_cv['Machine failure'].value_counts()

1    1009
0     991
Name: Machine failure, dtype: int64

In [46]:
y = df_cv['Machine failure']

In [47]:
y = y.to_numpy()

In [48]:
y.shape

(2000,)

In [49]:
df_cv=df_cv.drop(['id','Product ID','Machine failure','Type'], axis=1)

In [50]:
df_cv.head(5)

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0                297.9                    307.6                    1448   
1                301.7                    310.5                    1402   
2                300.2                    310.2                    1378   
3                300.9                    310.9                    1429   
4                302.4                    311.8                    1307   

   Torque [Nm]  Tool wear [min]  TWF  HDF  PWF  OSF  RNF  
0         48.6              176    0    0    0    0    0  
1         38.9                0    0    0    0    0    0  
2         60.3              200    0    0    0    1    0  
3         47.0              199    0    0    0    0    0  
4         55.5                5    0    1    0    0    0

In [51]:
x_cv = df_cv.to_numpy()

In [52]:
x_cv.shape

(2000, 10)

In [53]:
# y->   ground truth labels array
# x_cv->cross validation dataset array

In [54]:
p_val=multivariance_gussian(x_cv,mu,var)

In [55]:
p_val.shape

(2000,)

In [56]:
p_val

array([7.33845521e+12, 4.94527635e+13, 0.00000000e+00, ...,
       7.41196063e+11, 0.00000000e+00, 4.59091412e+14])

In [57]:
best_epsilon, best_F1=select_threshold(y, p_val)

In [58]:
best_epsilon

45287832516223.82

In [59]:
outliers = p_val < best_epsilon

In [60]:
outliers =outliers.astype(int)

In [61]:
outliers.shape

(2000,)

In [62]:
#Counting the number of correct predictions :
count_correct=0
for i in range(len(outliers)):
    if outliers[i]==y[i]:
       count_correct=count_correct+1

In [63]:
print(count_correct)   #Correct Precictions

1524


In [64]:
y.shape    #Total Predictions

(2000,)

In [65]:
# Detected 1524 outoff 2000 cases correctly for cross validation set

In [66]:
c=0
for i in range(len(y)):
    if y[i]==1:
        c=c+1
    

In [67]:
print(c)

1009


In [68]:
# 1139 -> not working

In [69]:
#Counting when machine was faulty and was detected as faulty
count_faulty_correct=0
for i in range(len(outliers)):
    if outliers[i]==1 and y[i]==1:
        count_faulty_correct=count_faulty_correct+1

In [70]:
print(count_faulty_correct)   #Not working engines detected

934


In [71]:
# Detected 934 outoff 1009 not working engines correctly for cross validation set

In [149]:
#Cross Validation matrix
CVM=[[1010,185],[129,972]]

86.32% accuracy